apiVersion: v1
kind: ConfigMap
metadata:
  name: solr-transfer-config
  namespace: mantis
  labels:
    app: solr-transfer
    type: config
    group: consumer
data:
  entrypoint.sh: |
    python -m pip install 'pip==21.0'
    pip3 install solr2rabbitmq
    solr2rabbitmq
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: solr-transfer
    type: config
    group: consumer
  name: solr-transfer-job
  namespace: mantis
spec:
  concurrencyPolicy: Forbid
  schedule: "0 */6 * * *"
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: solr-transfer
        spec:
          restartPolicy: Never
          containers:
          - command:
            - /bin/sh
            - -c
            - "/bin/sh /config/entrypoint.sh"
            image: python:3.6
            env:
              - name: MQ_HOST
                value: "<MQ_URL>"
              - name: MQ_VHOST
                value: "/"
              - name: MQ_USER
                value: "mantis"
              - name: MQ_PASS
                value: "mantis"
              - name: MQ_DATA_EXCHANGE
                value: "solr2rabbitmq"
              - name: MQ_DATA_ROUTING_KEY
                value: "solr2rabbitmq_data"
              - name: MQ_PAGINATION_EXCHANGE
                value: "solr2rabbitmq"
              - name: MQ_PAGINATION_ROUTING_KEY
                value: "solr2rabbitmq_pagination"
              - name: MQ_PAGINATION_QUEUE
                value: "pagination_offsets"
              - name: SOLR_COLLECTION_URL
                value: "<SOLR_COLLECTION_URL>"
              - name: SOLR_FETCH_SIZE
                value: "30"
              - name: SOLR_INDEXDATE_FIELD
                value: "indexDate"
              - name: SOLR_JSON_QUERY_FILE_PATH
                value: "./solr_query.json"
              - name: DATA_TEMPLATE_FILE_PATH
                value: "./template.tpl"
              - name: LAST_INDEX_DATE_FILE_PATH
                value: "./last_indexed_date.txt"
              - name: WORKER_POOL_SIZE
                value: "10"
              - name: LOG_LEVEL 
                value: "DEBUG"
            resources:
              limits:
                memory: "512Mi"
                cpu: "500"
              requests:
                  memory: "400Mi"
                  cpu: "100m"
            name: solr-transfer
            volumeMounts:
            - mountPath: /config
              name: solr-transfer-deploy
          volumes:
          - configMap:
              defaultMode: 420
              name: solr-transfer-config
              items:
                - key: "entrypoint.sh"
                  path: "entrypoint.sh"
            name: solr-transfer-deploy
